sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
env:
- ARGS=""
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script: 
- sudo apt-get install texlive texlive-xetex
- stack $ARGS --no-terminal --install-ghc build 
- stack $ARGS --no-terminal --install-ghc ghc includes.hs -- -o includes
- stack $ARGS --no-terminal --install-ghc exec make html
# Run the example test suite
- sudo apt-get install libblas-dev liblapack-dev
- cd src && bash ./ci
cache:
  directories:
  - $HOME/.stack
  - .stack-work
